version: "3"
services:
  postgres:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - common-net
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    links:
      - postgres
    restart: always
    networks:
      - common-net

networks:
  common-net: {}
